### ISSUE TITLE
Creating the converter to LHaloTrees from TreeFrog output

### ISSUE THREAD

**Issue by manodeep** [manodeep/genesis#1]
Most of the work is already done by @jacobseiler, the last remaining bit is to account for flybys in the simulation. An implementation is [here](https://github.com/manodeep/ConvertCTrees/blob/master/convert_trees_to_lhalo.c#L1052-L1136)

**Comment by jacobseiler** [comment]
Under ``Settings`` in my fork was an option to allow issues on my fork.  [I've opened this issue on that fork to keep it tidy](https://github.com/jacobseiler/genesis/issues/1).
